
name = "DashGantt"
uuid = "1b08a953-4be3-4667-9a23-cbd73af4db30"
authors = ["Evan Rasmussen <evanras@umich.edu>"]
version = "0.0.7"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
